-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 删除现有策略并重新创建
DROP POLICY IF EXISTS "允许查看用户" ON public.users;
DROP POLICY IF EXISTS "允许创建用户" ON public.users;
DROP POLICY IF EXISTS "允许更新用户" ON public.users;

-- 重新创建策略
CREATE POLICY "允许查看用户" ON public.users FOR SELECT USING (true);
CREATE POLICY "允许创建用户" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "允许更新用户" ON public.users FOR UPDATE USING (true);