-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建默认角色
INSERT INTO roles (name, description, is_system) VALUES 
('super_admin', '超级管理员，拥有系统全部权限', true),
('project_manager', '项目经理，管理项目及乙方单位', true),
('finance', '财务，负责发票和付款管理', true),
('material_staff', '材料员，负责物资管理', true),
('mechanical_staff', '机械员，负责机械管理', true),
('labor_staff', '劳资员，负责劳务管理', true)
ON CONFLICT (name) DO NOTHING;

-- 创建默认权限
INSERT INTO permissions (code, name, module, description) VALUES 
('project_read', '查看项目', 'project', '查看项目列表和详情'),
('project_create', '创建项目', 'project', '创建新项目'),
('project_update', '编辑项目', 'project', '编辑项目信息'),
('project_delete', '删除项目', 'project', '删除项目'),
('finance_read', '查看财务', 'finance', '查看发票和付款记录'),
('finance_create', '创建财务记录', 'finance', '创建发票和付款记录'),
('base_data_read', '查看基础数据', 'base_data', '查看基础数据'),
('base_data_manage', '管理基础数据', 'base_data', '管理甲方/签约/乙方单位'),
('seal_read', '查看印章', 'seal', '查看印章记录'),
('seal_manage', '管理印章', 'seal', '用章申请和审批'),
('warning_read', '查看预警', 'warning', '查看预警信息'),
('admin_manage', '系统管理', 'admin', '用户和权限管理')
ON CONFLICT (code) DO NOTHING;

-- 为超级管理员角色分配所有权限
INSERT INTO role_permissions (role_id, permission_id, can_read, can_create, can_update, can_delete, can_approve)
SELECT r.id, p.id, true, true, true, true, true
FROM roles r, permissions p
WHERE r.name = 'super_admin'
ON CONFLICT DO NOTHING;

-- 为项目经理分配部分权限
INSERT INTO role_permissions (role_id, permission_id, can_read, can_create, can_update, can_delete, can_approve)
SELECT r.id, p.id, 
  CASE WHEN p.code IN ('project_read', 'project_create', 'project_update', 'seal_read', 'seal_manage', 'warning_read', 'base_data_read') THEN true ELSE false END,
  CASE WHEN p.code IN ('project_create', 'seal_manage') THEN true ELSE false END,
  CASE WHEN p.code IN ('project_update', 'seal_manage') THEN true ELSE false END,
  false,
  false
FROM roles r, permissions p
WHERE r.name = 'project_manager'
ON CONFLICT DO NOTHING;

-- 为财务分配财务权限
INSERT INTO role_permissions (role_id, permission_id, can_read, can_create, can_update, can_delete, can_approve)
SELECT r.id, p.id, true, true, true, false, true
FROM roles r, permissions p
WHERE r.name = 'finance' AND p.module IN ('finance', 'warning_read')
ON CONFLICT DO NOTHING;