-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 修复 party_a 表的 RLS 策略，允许匿名用户读取
ALTER TABLE party_a ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow_read_party_a" ON party_a;
CREATE POLICY "allow_read_party_a" ON party_a FOR SELECT USING (true);

DROP POLICY IF EXISTS "allow_insert_party_a" ON party_a;
CREATE POLICY "allow_insert_party_a" ON party_a FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "allow_update_party_a" ON party_a;
CREATE POLICY "allow_update_party_a" ON party_a FOR UPDATE USING (true);

DROP POLICY IF EXISTS "allow_delete_party_a" ON party_a;
CREATE POLICY "allow_delete_party_a" ON party_a FOR DELETE USING (true);

-- 修复 storage 策略
DROP POLICY IF EXISTS "allow_all_storage_access" ON storage.objects;
CREATE POLICY "allow_all_storage_access" ON storage.objects FOR ALL USING (true) WITH CHECK (true);