-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 操作日志表
CREATE TABLE IF NOT EXISTS operation_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  username VARCHAR(100),
  ip_address VARCHAR(50),
  module VARCHAR(100),
  action_type VARCHAR(50),
  description TEXT,
  request_params JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 备份记录表
CREATE TABLE IF NOT EXISTS backup_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  backup_type VARCHAR(20),
  status VARCHAR(20),
  file_size VARCHAR(50),
  file_path TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 备份设置表
CREATE TABLE IF NOT EXISTS backup_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  auto_backup_enabled BOOLEAN DEFAULT true,
  backup_frequency VARCHAR(20) DEFAULT 'daily',
  backup_time TIME DEFAULT '02:00',
  retain_count INTEGER DEFAULT 7,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 初始化备份设置
INSERT INTO backup_settings (auto_backup_enabled, backup_frequency, backup_time, retain_count)
VALUES (true, 'daily', '02:00', 7)
ON CONFLICT DO NOTHING;

-- 启用RLS
ALTER TABLE operation_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_settings ENABLE ROW LEVEL SECURITY;

-- 允许所有人查看操作日志
CREATE POLICY "允许查看操作日志" ON operation_logs FOR SELECT USING (true);
CREATE POLICY "允许创建操作日志" ON operation_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "允许查看备份记录" ON backup_logs FOR SELECT USING (true);
CREATE POLICY "允许创建备份记录" ON backup_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "允许查看备份设置" ON backup_settings FOR SELECT USING (true);
CREATE POLICY "允许更新备份设置" ON backup_settings FOR UPDATE USING (true);