-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS code VARCHAR(50) UNIQUE;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS permissions TEXT[] DEFAULT '{}';