-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE public.project_archive (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  project_deposit NUMERIC(15,2) DEFAULT 0,
  project_deposit_remark TEXT,
  bid_bond NUMERIC(15,2) DEFAULT 0,
  bid_bond_remark TEXT,
  quality_bond NUMERIC(15,2) DEFAULT 0,
  quality_bond_remark TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.project_archive ENABLE ROW LEVEL SECURITY;

CREATE POLICY "公开读取" ON public.project_archive FOR SELECT USING (true);
CREATE POLICY "公开插入" ON public.project_archive FOR INSERT WITH CHECK (true);
CREATE POLICY "公开更新" ON public.project_archive FOR UPDATE USING (true);
CREATE POLICY "管理员删除" ON public.project_archive FOR DELETE USING (true);