-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 收款登记表
CREATE TABLE receipt_registration (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  receipt_no VARCHAR(50) NOT NULL UNIQUE,
  title VARCHAR(200) NOT NULL,
  project_id UUID NOT NULL,
  income_category VARCHAR(50),
  contract_id UUID,
  bank_account_id UUID,
  payer_id UUID,
  payer_name VARCHAR(200),
  payee_company_id UUID NOT NULL,
  payment_method VARCHAR(50),
  amount DECIMAL(15,2) NOT NULL,
  handler VARCHAR(100) NOT NULL,
  receipt_date DATE NOT NULL,
  remark TEXT,
  images TEXT,
  status VARCHAR(20) DEFAULT '有效',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE receipt_registration ENABLE ROW LEVEL SECURITY;

-- 允许所有操作
CREATE POLICY "allow_all_receipt_registration" ON receipt_registration FOR ALL USING (true) WITH CHECK (true);

COMMENT ON TABLE receipt_registration IS '收款登记表';
COMMENT ON COLUMN receipt_registration.receipt_no IS '登记单号';
COMMENT ON COLUMN receipt_registration.title IS '登记主题';
COMMENT ON COLUMN receipt_registration.project_id IS '所属项目ID';
COMMENT ON COLUMN receipt_registration.income_category IS '收入类别';
COMMENT ON COLUMN receipt_registration.contract_id IS '关联收入合同ID';
COMMENT ON COLUMN receipt_registration.bank_account_id IS '资金账户ID';
COMMENT ON COLUMN receipt_registration.payer_id IS '付款方ID（甲方单位）';
COMMENT ON COLUMN receipt_registration.payer_name IS '付款方名称';
COMMENT ON COLUMN receipt_registration.payee_company_id IS '收款方公司ID';
COMMENT ON COLUMN receipt_registration.payment_method IS '收款方式';
COMMENT ON COLUMN receipt_registration.amount IS '收款金额';
COMMENT ON COLUMN receipt_registration.handler IS '经办人';
COMMENT ON COLUMN receipt_registration.receipt_date IS '收款日期';
COMMENT ON COLUMN receipt_registration.images IS '图片路径，多个用逗号分隔';