-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE POLICY "allow_all_storage_access" ON storage.objects FOR ALL USING (true) WITH CHECK (true);