-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================


-- 角色枚举
CREATE TYPE app_role AS ENUM ('super_admin', 'finance', 'project_manager', 'material_staff', 'mechanical_staff', 'labor_staff', 'supplier', 'labor_team');

-- 用户档案表
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  real_name TEXT,
  phone TEXT,
  avatar_url TEXT,
  role app_role NOT NULL DEFAULT 'project_manager',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 项目表
CREATE TABLE public.projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  bid_amount DECIMAL(15,2) DEFAULT 0,
  duration VARCHAR(100),
  start_date DATE,
  end_date DATE,
  project_manager VARCHAR(100),
  manager_phone VARCHAR(20),
  manager_id_card VARCHAR(18),
  manager_id_card_file TEXT,
  management_fee_rate DECIMAL(5,2) DEFAULT 0,
  tax_rate DECIMAL(5,2) DEFAULT 0,
  owner_name VARCHAR(255),
  owner_credit_code VARCHAR(18),
  owner_address TEXT,
  owner_bank VARCHAR(255),
  owner_account VARCHAR(50),
  owner_contact VARCHAR(100),
  owner_contact_phone VARCHAR(20),
  status VARCHAR(20) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 附件类型枚举
CREATE TYPE attachment_type AS ENUM ('contract', 'bid_notice', 'insurance', 'internal_contract', 'id_card', 'guarantee_letter', 'counter_guarantee', 'budget', 'settlement', 'audit_report', 'other');

-- 项目附件表
CREATE TABLE public.project_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  attachment_type attachment_type NOT NULL,
  file_name VARCHAR(255),
  file_url TEXT,
  uploaded_at TIMESTAMP DEFAULT NOW(),
  uploaded_by UUID REFERENCES public.profiles(id)
);

-- 供应商表
CREATE TABLE public.suppliers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  supply_category VARCHAR(50),
  supply_content TEXT,
  contract_amount DECIMAL(15,2) DEFAULT 0,
  contract_file TEXT,
  business_license TEXT,
  bank_account VARCHAR(50),
  bank_name VARCHAR(255),
  status VARCHAR(20) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 成本发票表
CREATE TABLE public.cost_invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  supplier_id UUID REFERENCES public.suppliers(id) ON DELETE SET NULL,
  invoice_type VARCHAR(10),
  invoice_number VARCHAR(100),
  invoice_amount DECIMAL(15,2) NOT NULL,
  deductible_tax DECIMAL(15,2),
  is_paid BOOLEAN DEFAULT FALSE,
  payment_record_id UUID,
  invoice_date DATE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 付款记录表
CREATE TABLE public.payment_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  supplier_id UUID REFERENCES public.suppliers(id) ON DELETE SET NULL,
  payment_type VARCHAR(50),
  amount DECIMAL(15,2) NOT NULL,
  transfer_date DATE,
  transfer_account VARCHAR(50),
  invoice_id UUID REFERENCES public.cost_invoices(id),
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 物资清单表
CREATE TABLE public.materials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  material_code VARCHAR(50),
  material_name VARCHAR(255) NOT NULL,
  unit VARCHAR(20),
  budget_quantity DECIMAL(15,3),
  budget_unit_price DECIMAL(15,2),
  created_at TIMESTAMP DEFAULT NOW()
);

-- 物资采购表
CREATE TABLE public.material_purchases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  material_id UUID REFERENCES public.materials(id) ON DELETE SET NULL,
  supplier_id UUID REFERENCES public.suppliers(id) ON DELETE SET NULL,
  quantity DECIMAL(15,3) NOT NULL,
  unit_price DECIMAL(15,2) NOT NULL,
  total_amount DECIMAL(15,2),
  purchase_date DATE,
  receipt_file TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 机械台班表
CREATE TABLE public.machine_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  week_start_date DATE NOT NULL,
  usage_amount DECIMAL(15,2),
  confirm_file TEXT,
  confirmed_at TIMESTAMP DEFAULT NOW(),
  confirmed_by UUID REFERENCES public.profiles(id)
);

-- 劳务班组表
CREATE TABLE public.labor_teams (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  team_name VARCHAR(255) NOT NULL,
  leader_name VARCHAR(100),
  leader_phone VARCHAR(20),
  monthly_output DECIMAL(15,2),
  output_month DATE,
  voucher_file TEXT,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 印章类型枚举
CREATE TYPE seal_type AS ENUM ('project_seal', 'temp_seal', 'seal_borrow');

-- 印章表
CREATE TABLE public.seals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  seal_type seal_type NOT NULL,
  file_url TEXT,
  status VARCHAR(20) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 印章外借表
CREATE TABLE public.seal_borrows (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  seal_id UUID REFERENCES public.seals(id) ON DELETE CASCADE,
  borrower_name VARCHAR(100),
  borrower_phone VARCHAR(20),
  purpose TEXT,
  expected_return_date DATE,
  actual_return_date DATE,
  status VARCHAR(20) DEFAULT 'borrowed',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 农民工档案表
CREATE TABLE public.workers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  id_card VARCHAR(18) NOT NULL,
  position VARCHAR(50),
  wage_standard DECIMAL(15,2),
  education_records TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 考勤记录表
CREATE TABLE public.attendance (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  worker_id UUID REFERENCES public.workers(id) ON DELETE CASCADE,
  month DATE NOT NULL,
  work_days INTEGER DEFAULT 0,
  overtime_hours DECIMAL(5,2),
  created_at TIMESTAMP DEFAULT NOW()
);

-- 工资支付记录表
CREATE TABLE public.wage_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  worker_id UUID REFERENCES public.workers(id) ON DELETE CASCADE,
  payment_month DATE NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  payment_date DATE,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 预警记录表
CREATE TABLE public.warnings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  warning_type VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cost_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.material_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machine_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.labor_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seal_borrows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wage_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warnings ENABLE ROW LEVEL SECURITY;

-- 公开读取策略
CREATE POLICY "公开读取" ON public.projects FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.suppliers FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.cost_invoices FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.payment_records FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.materials FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.material_purchases FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.machine_usage FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.labor_teams FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.seals FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.seal_borrows FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.workers FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.attendance FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.wage_payments FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.warnings FOR SELECT USING (true);
CREATE POLICY "公开读取" ON public.project_attachments FOR SELECT USING (true);

-- 公开写入策略
CREATE POLICY "公开插入" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.suppliers FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.cost_invoices FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.payment_records FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.materials FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.material_purchases FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.machine_usage FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.labor_teams FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.seals FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.seal_borrows FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.workers FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.attendance FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.wage_payments FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.warnings FOR INSERT WITH CHECK (true);
CREATE POLICY "公开插入" ON public.project_attachments FOR INSERT WITH CHECK (true);

-- 公开更新策略
CREATE POLICY "公开更新" ON public.projects FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.profiles FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.suppliers FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.cost_invoices FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.payment_records FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.materials FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.material_purchases FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.machine_usage FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.labor_teams FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.seals FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.seal_borrows FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.workers FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.attendance FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.wage_payments FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.warnings FOR UPDATE USING (true);
CREATE POLICY "公开更新" ON public.project_attachments FOR UPDATE USING (true);

-- 公开删除策略（仅管理员）
CREATE POLICY "管理员删除" ON public.projects FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.profiles FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.suppliers FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.cost_invoices FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.payment_records FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.materials FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.material_purchases FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.machine_usage FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.labor_teams FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.seals FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.seal_borrows FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.workers FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.attendance FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.wage_payments FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.warnings FOR DELETE USING (true);
CREATE POLICY "管理员删除" ON public.project_attachments FOR DELETE USING (true);
