-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "允许所有操作" ON public.users;
CREATE POLICY "允许所有操作" ON public.users FOR ALL USING (true) WITH CHECK (true);