-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建用户表
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 允许所有人查看用户列表
CREATE POLICY "允许查看用户" ON public.users FOR SELECT USING (true);

-- 允许所有人创建用户
CREATE POLICY "允许创建用户" ON public.users FOR INSERT WITH CHECK (true);

-- 允许所有人更新用户
CREATE POLICY "允许更新用户" ON public.users FOR UPDATE USING (true);

-- 插入默认管理员账号 (密码: admin123)
INSERT INTO public.users (username, password, role) VALUES 
('admin', 'admin123', 'admin')
ON CONFLICT (username) DO NOTHING;