-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE income_invoices ADD COLUMN tax_paid_at TIMESTAMP DEFAULT NULL;