-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE cost_invoices DROP CONSTRAINT cost_invoices_supplier_id_fkey;
ALTER TABLE cost_invoices ADD CONSTRAINT cost_invoices_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES party_b(id) ON DELETE SET NULL;