-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 修复 income_invoices 表的 RLS 策略
ALTER TABLE income_invoices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow_read_income_invoices" ON income_invoices;
CREATE POLICY "allow_read_income_invoices" ON income_invoices FOR SELECT USING (true);

DROP POLICY IF EXISTS "allow_insert_income_invoices" ON income_invoices;
CREATE POLICY "allow_insert_income_invoices" ON income_invoices FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "allow_update_income_invoices" ON income_invoices;
CREATE POLICY "allow_update_income_invoices" ON income_invoices FOR UPDATE USING (true);

DROP POLICY IF EXISTS "allow_delete_income_invoices" ON income_invoices;
CREATE POLICY "allow_delete_income_invoices" ON income_invoices FOR DELETE USING (true);