-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 甲方单位表
CREATE TABLE IF NOT EXISTS party_a (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(200) NOT NULL,
  unit_type VARCHAR(50),
  credit_code VARCHAR(50),
  bank_name VARCHAR(200),
  legal_person VARCHAR(100),
  bank_account VARCHAR(100),
  phone VARCHAR(50),
  remark TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 签约单位表
CREATE TABLE IF NOT EXISTS signatory_units (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_name VARCHAR(200) NOT NULL,
  unit_code VARCHAR(50) UNIQUE,
  credit_code VARCHAR(50),
  contact_person VARCHAR(100),
  contact_phone VARCHAR(50),
  office_address TEXT,
  invoice_title VARCHAR(200),
  tax_number VARCHAR(50),
  tax_disk_no VARCHAR(50),
  bank_name VARCHAR(200),
  bank_account VARCHAR(100),
  address TEXT,
  email VARCHAR(100),
  tax_province VARCHAR(50),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 乙方单位表
CREATE TABLE IF NOT EXISTS party_b (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_name VARCHAR(200) NOT NULL,
  unit_type VARCHAR(50),
  taxpayer_type VARCHAR(50),
  fax VARCHAR(50),
  is_certified BOOLEAN DEFAULT false,
  credit_code VARCHAR(50),
  bank_name VARCHAR(200),
  bank_account VARCHAR(100),
  legal_representative VARCHAR(100),
  phone VARCHAR(50),
  business_license_file TEXT,
  account_license_file TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE party_a ENABLE ROW LEVEL SECURITY;
ALTER TABLE signatory_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_b ENABLE ROW LEVEL SECURITY;

-- RLS策略
CREATE POLICY "所有人可查看甲方单位" ON party_a FOR SELECT USING (true);
CREATE POLICY "所有人可创建甲方单位" ON party_a FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新甲方单位" ON party_a FOR UPDATE USING (true);
CREATE POLICY "管理员可删除甲方单位" ON party_b FOR DELETE USING (true);

CREATE POLICY "所有人可查看签约单位" ON signatory_units FOR SELECT USING (true);
CREATE POLICY "所有人可创建签约单位" ON signatory_units FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新签约单位" ON signatory_units FOR UPDATE USING (true);
CREATE POLICY "管理员可删除签约单位" ON signatory_units FOR DELETE USING (true);

CREATE POLICY "所有人可查看乙方单位" ON party_b FOR SELECT USING (true);
CREATE POLICY "所有人可创建乙方单位" ON party_b FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新乙方单位" ON party_b FOR UPDATE USING (true);
CREATE POLICY "管理员可删除乙方单位" ON party_b FOR DELETE USING (true);