-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS seal_usage_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  usage_type VARCHAR(20) NOT NULL,
  usage_reason TEXT NOT NULL,
  borrower_name VARCHAR(100),
  borrower_id_card_file TEXT,
  expected_return_date TIMESTAMP,
  actual_return_date TIMESTAMP,
  attachment_files TEXT[],
  remarks TEXT,
  seal_id UUID REFERENCES seals(id),
  status VARCHAR(20) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE seal_usage_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "所有人可查看用章记录" ON seal_usage_records FOR SELECT USING (true);
CREATE POLICY "所有人可创建用章记录" ON seal_usage_records FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新用章记录" ON seal_usage_records FOR UPDATE USING (true);
