-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 重新创建 party_b 表的 RLS 策略，确保匿名用户可以插入
DROP POLICY IF EXISTS "所有人可创建乙方单位" ON public.party_b;
DROP POLICY IF EXISTS "所有人可更新乙方单位" ON public.party_b;
DROP POLICY IF EXISTS "所有人可查看乙方单位" ON public.party_b;
DROP POLICY IF EXISTS "管理员可删除乙方单位" ON public.party_b;

-- 重新创建策略
CREATE POLICY "所有人可查看乙方单位" ON public.party_b FOR SELECT USING (true);
CREATE POLICY "所有人可创建乙方单位" ON public.party_b FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新乙方单位" ON public.party_b FOR UPDATE USING (true);
CREATE POLICY "管理员可删除乙方单位" ON public.party_b FOR DELETE USING (true);