-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  is_system BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS permissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  module VARCHAR(50) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS role_permissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  role_id UUID REFERENCES roles(id) ON DELETE CASCADE,
  permission_id UUID REFERENCES permissions(id) ON DELETE CASCADE,
  can_create BOOLEAN DEFAULT false,
  can_read BOOLEAN DEFAULT true,
  can_update BOOLEAN DEFAULT false,
  can_delete BOOLEAN DEFAULT false,
  can_approve BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS backup_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  backup_type VARCHAR(20) DEFAULT 'daily',
  backup_time TIMESTAMP DEFAULT NOW(),
  backup_size TEXT,
  status VARCHAR(20) DEFAULT 'success',
  error_message TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "管理员可管理角色" ON roles FOR ALL USING (true);
CREATE POLICY "管理员可管理权限" ON permissions FOR ALL USING (true);
CREATE POLICY "管理员可管理角色权限" ON role_permissions FOR ALL USING (true);
CREATE POLICY "所有人可查看备份日志" ON backup_logs FOR SELECT USING (true);
CREATE POLICY "管理员可写入备份日志" ON backup_logs FOR INSERT WITH CHECK (true);

INSERT INTO roles (name, description, is_system) VALUES 
('super_admin', '超级管理员', true),
('finance', '财务', true),
('project_manager', '项目经理', true),
('material_staff', '材料员', true),
('labor_staff', '劳资员', true),
('supplier', '外部供应商', true);

INSERT INTO permissions (code, name, module) VALUES 
('project_read', '查看项目', 'project'),
('project_create', '创建项目', 'project'),
('project_update', '编辑项目', 'project'),
('project_delete', '删除项目', 'project'),
('finance_read', '查看财务', 'finance'),
('finance_create', '创建财务', 'finance'),
('finance_update', '编辑财务', 'finance'),
('finance_delete', '删除财务', 'finance'),
('supplier_read', '查看供应商', 'supplier'),
('supplier_create', '创建供应商', 'supplier'),
('supplier_update', '编辑供应商', 'supplier'),
('supplier_delete', '删除供应商', 'supplier'),
('seal_read', '查看印章', 'seal'),
('seal_create', '申请印章', 'seal'),
('seal_approve', '审批印章', 'seal'),
('worker_read', '查看农民工', 'worker'),
('worker_create', '创建农民工', 'worker'),
('worker_update', '编辑农民工', 'worker'),
('worker_delete', '删除农民工', 'worker'),
('material_read', '查看物资', 'material'),
('material_create', '创建物资', 'material'),
('material_update', '编辑物资', 'material'),
('material_delete', '删除物资', 'material'),
('role_manage', '角色管理', 'system'),
('backup_manage', '备份管理', 'system');

INSERT INTO role_permissions (role_id, permission_id, can_create, can_read, can_update, can_delete, can_approve)
SELECT r.id, p.id, true, true, true, true, true
FROM roles r, permissions p WHERE r.name = 'super_admin';

INSERT INTO role_permissions (role_id, permission_id, can_create, can_read, can_update, can_delete, can_approve)
SELECT r.id, p.id, 
  CASE WHEN p.code IN ('finance_create', 'finance_update', 'supplier_read') THEN true ELSE false END,
  true,
  CASE WHEN p.code IN ('finance_update', 'supplier_read') THEN true ELSE false END,
  false,
  false
FROM roles r, permissions p WHERE r.name = 'finance';

INSERT INTO role_permissions (role_id, permission_id, can_create, can_read, can_update, can_delete, can_approve)
SELECT r.id, p.id,
  CASE WHEN p.code IN ('project_create', 'project_update', 'seal_create', 'worker_create', 'worker_update') THEN true ELSE false END,
  true,
  CASE WHEN p.code IN ('project_update', 'worker_update') THEN true ELSE false END,
  false,
  CASE WHEN p.code IN ('project_update') THEN true ELSE false END
FROM roles r, permissions p WHERE r.name = 'project_manager';

INSERT INTO role_permissions (role_id, permission_id, can_create, can_read, can_update, can_delete, can_approve)
SELECT r.id, p.id,
  CASE WHEN p.code IN ('material_create', 'material_update') THEN true ELSE false END,
  true,
  CASE WHEN p.code IN ('material_update') THEN true ELSE false END,
  false,
  false
FROM roles r, permissions p WHERE r.name = 'material_staff';

INSERT INTO role_permissions (role_id, permission_id, can_create, can_read, can_update, can_delete, can_approve)
SELECT r.id, p.id,
  CASE WHEN p.code IN ('worker_create', 'worker_update') THEN true ELSE false END,
  true,
  CASE WHEN p.code IN ('worker_update') THEN true ELSE false END,
  false,
  false
FROM roles r, permissions p WHERE r.name = 'labor_staff';

INSERT INTO role_permissions (role_id, permission_id, can_create, can_read, can_update, can_delete, can_approve)
SELECT r.id, p.id, false, true, false, false, false
FROM roles r, permissions p WHERE r.name = 'supplier';
