-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS project_suppliers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL,
  supplier_name VARCHAR(200) NOT NULL,
  supply_category VARCHAR(50) NOT NULL,
  supply_content TEXT,
  contract_amount DECIMAL(15,2),
  contract_file TEXT,
  business_license_file TEXT,
  bank_account VARCHAR(100),
  bank_name VARCHAR(200),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE project_suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看项目供应商" ON project_suppliers FOR SELECT USING (true);
CREATE POLICY "所有人可创建项目供应商" ON project_suppliers FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新项目供应商" ON project_suppliers FOR UPDATE USING (true);
CREATE POLICY "所有人可删除项目供应商" ON project_suppliers FOR DELETE USING (true);

CREATE INDEX idx_project_suppliers_project ON project_suppliers(project_id);