-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE projects ADD COLUMN party_a_id UUID REFERENCES party_a(id) ON DELETE SET NULL;
ALTER TABLE projects ADD COLUMN signatory_id UUID REFERENCES signatory_units(id) ON DELETE SET NULL;