-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 禁用users表的RLS
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;