-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE income_invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  company_id UUID NOT NULL REFERENCES companies(id),
  invoice_type VARCHAR(20) DEFAULT '普票',
  tax_rate DECIMAL(5,2) DEFAULT 0,
  buyer_id UUID REFERENCES party_a(id),
  buyer_name VARCHAR(200) NOT NULL,
  buyer_tax_no VARCHAR(50) NOT NULL,
  buyer_bank VARCHAR(200),
  buyer_account VARCHAR(100),
  buyer_address_phone VARCHAR(500),
  invoice_amount DECIMAL(15,2) NOT NULL,
  tax_amount DECIMAL(15,2) NOT NULL,
  remark TEXT,
  tax_paid BOOLEAN DEFAULT false,
  tax_payment_method VARCHAR(50),
  tax_payment_voucher TEXT,
  invoice_photo TEXT,
  payment_description VARCHAR(500),
  status VARCHAR(20) DEFAULT '待审核',
  invoice_date TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE income_invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看收入发票" ON income_invoices FOR SELECT USING (true);
CREATE POLICY "所有人可创建收入发票" ON income_invoices FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新收入发票" ON income_invoices FOR UPDATE USING (true);
CREATE POLICY "所有人可删除收入发票" ON income_invoices FOR DELETE USING (true);