-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS other_incomes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES projects(id) ON DELETE SET NULL,
  company_id UUID REFERENCES companies(id) ON DELETE SET NULL,
  income_amount DECIMAL(15,2) DEFAULT 0,
  remark TEXT,
  source VARCHAR(200),
  voucher_images TEXT,
  income_date DATE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP
);

ALTER TABLE other_incomes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "公开读取" ON other_incomes FOR SELECT USING (true);
CREATE POLICY "公开插入" ON other_incomes FOR INSERT WITH CHECK (true);
CREATE POLICY "公开更新" ON other_incomes FOR UPDATE USING (true);
CREATE POLICY "公开删除" ON other_incomes FOR DELETE USING (true);