-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 项目其他收入表
CREATE TABLE IF NOT EXISTS project_other_income (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  income_date DATE NOT NULL,
  income_amount DECIMAL(15,2) NOT NULL,
  payer_name TEXT,
  remark TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 项目保证金记录表
CREATE TABLE IF NOT EXISTS project_deposit_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  bid_bond DECIMAL(15,2),
  bid_bond_remark TEXT,
  performance_bond DECIMAL(15,2),
  performance_bond_remark TEXT,
  quality_bond DECIMAL(15,2),
  quality_bond_remark TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 项目其他事项记录表
CREATE TABLE IF NOT EXISTS project_other_matters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  content TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE project_other_income ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_deposit_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_other_matters ENABLE ROW LEVEL SECURITY;

-- 创建策略（允许所有人查看和操作）
CREATE POLICY "允许所有操作" ON project_other_income FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "允许所有操作" ON project_deposit_records FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "允许所有操作" ON project_other_matters FOR ALL USING (true) WITH CHECK (true);