-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE seal_usage_records ADD COLUMN IF NOT EXISTS seal_type VARCHAR(50);
ALTER TABLE seal_usage_records ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES projects(id);
ALTER TABLE seal_usage_records ADD COLUMN IF NOT EXISTS project_name VARCHAR(255);