-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 收入合同主表
CREATE TABLE income_contracts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contract_name VARCHAR(255) NOT NULL,
  contract_code VARCHAR(50) UNIQUE,
  project_id UUID REFERENCES projects(id) ON DELETE SET NULL,
  party_a_id UUID REFERENCES party_a(id) ON DELETE SET NULL,
  contract_amount DECIMAL(15,2) DEFAULT 0,
  sign_date DATE,
  status VARCHAR(20) DEFAULT '草稿',
  attachment_url TEXT,
  scan_file_url TEXT,
  contract_period VARCHAR(100),
  payment_method TEXT,
  remark TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 收入合同补充协议
CREATE TABLE income_supplements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  supplement_code VARCHAR(50) UNIQUE,
  main_contract_id UUID REFERENCES income_contracts(id) ON DELETE CASCADE,
  supplement_name VARCHAR(255),
  supplement_amount DECIMAL(15,2) DEFAULT 0,
  sign_date DATE,
  attachment_url TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 收入合同变更签证
CREATE TABLE income_variations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  variation_code VARCHAR(50) UNIQUE,
  contract_id UUID REFERENCES income_contracts(id) ON DELETE CASCADE,
  variation_name VARCHAR(255),
  variation_amount DECIMAL(15,2) DEFAULT 0,
  variation_date DATE,
  attachment_url TEXT,
  approval_status VARCHAR(20) DEFAULT '待审核',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 收入合同扣款登记
CREATE TABLE income_deductions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  deduction_code VARCHAR(50) UNIQUE,
  contract_id UUID REFERENCES income_contracts(id) ON DELETE CASCADE,
  deduction_reason TEXT,
  deduction_amount DECIMAL(15,2) DEFAULT 0,
  deduction_date DATE,
  attachment_url TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 收入合同产值确认
CREATE TABLE income_output_confirmations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  confirmation_code VARCHAR(50) UNIQUE,
  contract_id UUID REFERENCES income_contracts(id) ON DELETE CASCADE,
  output_month VARCHAR(7),
  confirmation_amount DECIMAL(15,2) DEFAULT 0,
  confirmation_date DATE,
  attachment_url TEXT,
  status VARCHAR(20) DEFAULT '待确认',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 收入合同结算
CREATE TABLE income_settlements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  settlement_code VARCHAR(50) UNIQUE,
  contract_id UUID REFERENCES income_contracts(id) ON DELETE CASCADE,
  settlement_amount DECIMAL(15,2) DEFAULT 0,
  settlement_date DATE,
  attachment_url TEXT,
  status VARCHAR(20) DEFAULT '未结算',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 支出合同主表
CREATE TABLE expense_contracts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contract_name VARCHAR(255) NOT NULL,
  contract_code VARCHAR(50) UNIQUE,
  project_id UUID REFERENCES projects(id) ON DELETE SET NULL,
  party_b_id UUID REFERENCES party_b(id) ON DELETE SET NULL,
  contract_amount DECIMAL(15,2) DEFAULT 0,
  sign_date DATE,
  status VARCHAR(20) DEFAULT '草稿',
  contract_type VARCHAR(50),
  attachment_url TEXT,
  contract_period VARCHAR(100),
  payment_terms TEXT,
  tax_rate DECIMAL(5,2),
  invoice_type VARCHAR(20),
  remark TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 支出合同补充协议
CREATE TABLE expense_supplements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  supplement_code VARCHAR(50) UNIQUE,
  main_contract_id UUID REFERENCES expense_contracts(id) ON DELETE CASCADE,
  supplement_name VARCHAR(255),
  supplement_amount DECIMAL(15,2) DEFAULT 0,
  sign_date DATE,
  attachment_url TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 支出合同变更签证
CREATE TABLE expense_variations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  variation_code VARCHAR(50) UNIQUE,
  contract_id UUID REFERENCES expense_contracts(id) ON DELETE CASCADE,
  variation_name VARCHAR(255),
  variation_amount DECIMAL(15,2) DEFAULT 0,
  variation_date DATE,
  attachment_url TEXT,
  approval_status VARCHAR(20) DEFAULT '待审核',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 支出合同扣款登记
CREATE TABLE expense_deductions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  deduction_code VARCHAR(50) UNIQUE,
  contract_id UUID REFERENCES expense_contracts(id) ON DELETE CASCADE,
  deduction_reason TEXT,
  deduction_amount DECIMAL(15,2) DEFAULT 0,
  deduction_date DATE,
  attachment_url TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 支出合同履约
CREATE TABLE expense_performances (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contract_id UUID REFERENCES expense_contracts(id) ON DELETE CASCADE,
  performance_content TEXT,
  performance_ratio DECIMAL(5,2) DEFAULT 0,
  performance_date DATE,
  attachment_url TEXT,
  cumulative_amount DECIMAL(15,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 支出合同结算
CREATE TABLE expense_settlements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  settlement_code VARCHAR(50) UNIQUE,
  contract_id UUID REFERENCES expense_contracts(id) ON DELETE CASCADE,
  settlement_amount DECIMAL(15,2) DEFAULT 0,
  settlement_date DATE,
  attachment_url TEXT,
  status VARCHAR(20) DEFAULT '未结算',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE income_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE income_supplements ENABLE ROW LEVEL SECURITY;
ALTER TABLE income_variations ENABLE ROW LEVEL SECURITY;
ALTER TABLE income_deductions ENABLE ROW LEVEL SECURITY;
ALTER TABLE income_output_confirmations ENABLE ROW LEVEL SECURITY;
ALTER TABLE income_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_supplements ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_variations ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_deductions ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_performances ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_settlements ENABLE ROW LEVEL SECURITY;

-- 创建策略（允许所有人查看和创建）
CREATE POLICY "所有人可查看收入合同" ON income_contracts FOR SELECT USING (true);
CREATE POLICY "所有人可创建收入合同" ON income_contracts FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新收入合同" ON income_contracts FOR UPDATE USING (true);
CREATE POLICY "管理员可删除收入合同" ON income_contracts FOR DELETE USING (true);

CREATE POLICY "所有人可查看收入补充协议" ON income_supplements FOR SELECT USING (true);
CREATE POLICY "所有人可创建收入补充协议" ON income_supplements FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新收入补充协议" ON income_supplements FOR UPDATE USING (true);
CREATE POLICY "管理员可删除收入补充协议" ON income_supplements FOR DELETE USING (true);

CREATE POLICY "所有人可查看收入变更签证" ON income_variations FOR SELECT USING (true);
CREATE POLICY "所有人可创建收入变更签证" ON income_variations FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新收入变更签证" ON income_variations FOR UPDATE USING (true);
CREATE POLICY "管理员可删除收入变更签证" ON income_variations FOR DELETE USING (true);

CREATE POLICY "所有人可查看收入扣款" ON income_deductions FOR SELECT USING (true);
CREATE POLICY "所有人可创建收入扣款" ON income_deductions FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新收入扣款" ON income_deductions FOR UPDATE USING (true);
CREATE POLICY "管理员可删除收入扣款" ON income_deductions FOR DELETE USING (true);

CREATE POLICY "所有人可查看收入产值确认" ON income_output_confirmations FOR SELECT USING (true);
CREATE POLICY "所有人可创建收入产值确认" ON income_output_confirmations FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新收入产值确认" ON income_output_confirmations FOR UPDATE USING (true);
CREATE POLICY "管理员可删除收入产值确认" ON income_output_confirmations FOR DELETE USING (true);

CREATE POLICY "所有人可查看收入结算" ON income_settlements FOR SELECT USING (true);
CREATE POLICY "所有人可创建收入结算" ON income_settlements FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新收入结算" ON income_settlements FOR UPDATE USING (true);
CREATE POLICY "管理员可删除收入结算" ON income_settlements FOR DELETE USING (true);

CREATE POLICY "所有人可查看支出合同" ON expense_contracts FOR SELECT USING (true);
CREATE POLICY "所有人可创建支出合同" ON expense_contracts FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新支出合同" ON expense_contracts FOR UPDATE USING (true);
CREATE POLICY "管理员可删除支出合同" ON expense_contracts FOR DELETE USING (true);

CREATE POLICY "所有人可查看支出补充协议" ON expense_supplements FOR SELECT USING (true);
CREATE POLICY "所有人可创建支出补充协议" ON expense_supplements FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新支出补充协议" ON expense_supplements FOR UPDATE USING (true);
CREATE POLICY "管理员可删除支出补充协议" ON expense_supplements FOR DELETE USING (true);

CREATE POLICY "所有人可查看支出变更签证" ON expense_variations FOR SELECT USING (true);
CREATE POLICY "所有人可创建支出变更签证" ON expense_variations FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新支出变更签证" ON expense_variations FOR UPDATE USING (true);
CREATE POLICY "管理员可删除支出变更签证" ON expense_variations FOR DELETE USING (true);

CREATE POLICY "所有人可查看支出扣款" ON expense_deductions FOR SELECT USING (true);
CREATE POLICY "所有人可创建支出扣款" ON expense_deductions FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新支出扣款" ON expense_deductions FOR UPDATE USING (true);
CREATE POLICY "管理员可删除支出扣款" ON expense_deductions FOR DELETE USING (true);

CREATE POLICY "所有人可查看支出履约" ON expense_performances FOR SELECT USING (true);
CREATE POLICY "所有人可创建支出履约" ON expense_performances FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新支出履约" ON expense_performances FOR UPDATE USING (true);
CREATE POLICY "管理员可删除支出履约" ON expense_performances FOR DELETE USING (true);

CREATE POLICY "所有人可查看支出结算" ON expense_settlements FOR SELECT USING (true);
CREATE POLICY "所有人可创建支出结算" ON expense_settlements FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新支出结算" ON expense_settlements FOR UPDATE USING (true);
CREATE POLICY "管理员可删除支出结算" ON expense_settlements FOR DELETE USING (true);