-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 公司表
CREATE TABLE IF NOT EXISTS companies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  company_type TEXT NOT NULL CHECK (company_type IN ('总公司', '分公司')),
  parent_id UUID REFERENCES companies(id) ON DELETE SET NULL,
  credit_code TEXT,
  contact_person TEXT,
  contact_phone TEXT,
  status TEXT DEFAULT '启用' CHECK (status IN ('启用', '禁用')),
  remark TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 用户公司关联表
CREATE TABLE IF NOT EXISTS user_companies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  company_id UUID REFERENCES companies(id) ON DELETE CASCADE,
  role TEXT DEFAULT '员工' CHECK (role IN ('超级管理员', '公司管理员', '员工')),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, company_id)
);

-- 项目表增加 company_id
ALTER TABLE projects ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE SET NULL;

-- 乙方单位表增加 company_id
ALTER TABLE party_b ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE SET NULL;

-- 甲方单位表增加 company_id
ALTER TABLE party_a ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE SET NULL;

-- 供应商表增加 company_id
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE SET NULL;

-- 支出合同表增加 company_id
ALTER TABLE expense_contracts ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE SET NULL;

-- 收入合同表增加 company_id
ALTER TABLE income_contracts ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE SET NULL;

-- 成本发票表增加 company_id
ALTER TABLE cost_invoices ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE SET NULL;

-- 付款记录表增加 company_id
ALTER TABLE payment_records ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE SET NULL;

-- 印章使用记录表增加 company_id
ALTER TABLE seal_usage_records ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE SET NULL;

-- 启用 RLS
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_companies ENABLE ROW LEVEL SECURITY;

-- 创建策略
CREATE POLICY "允许所有操作" ON companies FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "允许所有操作" ON user_companies FOR ALL USING (true) WITH CHECK (true);

-- 插入默认总公司
INSERT INTO companies (name, company_type, status) VALUES ('默认总公司', '总公司', '启用');