-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================


ALTER TABLE cost_invoices ADD COLUMN IF NOT EXISTS attachment_url TEXT;
ALTER TABLE cost_invoices ADD COLUMN IF NOT EXISTS paid_amount NUMERIC DEFAULT 0;
ALTER TABLE cost_invoices ADD COLUMN IF NOT EXISTS remaining_amount NUMERIC DEFAULT 0;

ALTER TABLE payment_records ADD COLUMN IF NOT EXISTS attachment_url TEXT;
ALTER TABLE payment_records ADD COLUMN IF NOT EXISTS bank_account VARCHAR(50);
ALTER TABLE payment_records ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100);

ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS invoiced_amount NUMERIC DEFAULT 0;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS paid_amount NUMERIC DEFAULT 0;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS remaining_amount NUMERIC DEFAULT 0;
